# protocol.py

# HLS-Specific WebSocket Commands
COMMAND_REQUEST_HLS_STREAM = "request_hls_stream"
COMMAND_STOP_HLS_STREAM = "stop_hls_stream"
COMMAND_GET_HLS_URL = "get_hls_url"
COMMAND_HLS_SEEK = "hls_seek"
COMMAND_HLS_STATUS = "hls_status"

# HLS-Specific Error Codes
ERROR_HLS_STREAM_ACTIVE = "HLS_STREAM_ACTIVE"
ERROR_TRACK_ID_NOT_FOUND = "TRACK_ID_NOT_FOUND"
ERROR_FFMPEG_FAILED = "FFMPEG_FAILED"
ERROR_STREAM_NOT_ACTIVE = "STREAM_NOT_ACTIVE"
ERROR_UNAUTHORIZED = "UNAUTHORIZED"
ERROR_INVALID_COMMAND = "INVALID_COMMAND"
ERROR_INVALID_PARAMETERS = "INVALID_PARAMETERS"
ERROR_HLS_SEEK_FAILED = "HLS_SEEK_FAILED"

# HLS Stream States
HLS_STATE_PLAYING = "playing"
HLS_STATE_BUFFERING = "buffering"
HLS_STATE_STOPPED = "stopped"
HLS_STATE_ERROR = "error"

# WebSocket Message Types
MESSAGE_TYPE_STATUS_UPDATE = "status_update"
MESSAGE_TYPE_HLS_ERROR = "hls_error"
